### ISSUE TITLE
Error log dokuwiki Release 2023-04-04 "Jack Jackrum"

### ISSUE THREAD

**Issue by cardi-m** [LarsGit223/dokuwiki_note#24]
E_WARNING: Undefined array key 1
.../lib/plugins/note/syntax.php(103)
#0 .../lib/plugins/note/syntax.php(103): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/www/htdocs/w00...', 103)
#1 .../inc/parser/renderer.php(119): syntax_plugin_note->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#2 .../inc/parserutils.php(700): Doku_Renderer->plugin('note', Array, 4, '</note>')
#3 .../inc/parserutils.php(158): p_render('xhtml', Array, NULL)
#4 .../inc/parserutils.php(96): p_cached_output('/www/htdocs/w00...', 'xhtml', 'start')
#5 .../inc/Ui/PageView.php(68): p_wiki_xhtml('start', 0, true, '')
#6 .../inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#7 .../inc/template.php(100): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core('show')
#9 .../inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
#10 .../inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
#11 .../inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
#12 .../lib/tpl/dokuwiki/main.php(59): tpl_content()
#13 .../inc/actions.php(27): include('/www/htdocs/w00...')
#14 .../doku.php(126): act_dispatch()
#15 {main}

**Comment by cardi-m** [comment]
maybe it was no problem with the update to Release 2023-04-04 "Jack Jackrum" rather using PHP 8.x
